<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="LambdaExpression.fs" />
    <Compile Include="BetaReduction.fs" />
    <Compile Include="LambdaParser.fs" />
    <Compile Include="LambdaInterpreter.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FParsec" Version="1.1.1" />
  </ItemGroup>

</Project>